server:
  port: 8087
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productsdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    database-platform: org.hibernate.dialect.H2Dialect
